FROM python:latest

COPY . .

RUN apt-get update
RUN apt-get install -y iputils-ping htop tree
RUN pip3 install -r src/requirements.txt

ENV API_TOKEN=qwerty123

EXPOSE 8000

CMD ["python3", "src/main.py", "&&", "tail", "-f", "src/logs/log1.log"]
