name: Build Docker Image

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t clouds-lab3-app:latest -f $GITHUB_WORKSPACE/lab2/Dockerfile.good lab2
        
      - name: Create Artifacts directory
        run: mkdir -p $GITHUB_WORKSPACE/artifacts

      - name: Show Docker Image Details
        run: docker inspect clouds-lab3-app:latest > $GITHUB_WORKSPACE/artifacts/docker_image_details.json
      
      - name: Debug - List Artifacts Directory
        run: ls -R $GITHUB_WORKSPACE/artifacts
      
      - name: Print File contents
        run: cat $GITHUB_WORKSPACE/artifacts/docker_image_details.json

      - name: Upload Docker Image Details
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: $GITHUB_WORKSPACE/artifacts/docker_image_details.json
      